---
name: MentionsPM
version: 1.0.2
api:
- 3.0.0
main: nikipuh\Main
author: LeNick
permissions:
  mention.team:
    default: op
  mention.op:
    default: op
  mention.vip:
    default: op
...
